server:
  port: 9092
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/imooc-demo?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
  session:
    store-type: none

